name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Verificar se index.html existe
        run: |
          if [ ! -f public/index.html ]; then
            echo "Erro: public/index.html não encontrado."
            exit 1
          fi

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v4

      - name: Enviar artefato para Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: public

      - name: Publicar no GitHub Pages
        uses: actions/deploy-pages@v4